title: Project

files:
  sortable: true
  fields:
    cover:
      label: Project Cover
      type:  checkbox
      text:  Is this the project cover?

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 1/2

  skills:
    label: Skills
    type:  text
    width: 1/2

  summary:
    label: Summary
    type: text
    width: 1/1

  text:
    label: Text
    type:  textarea

  cover:
    label: Project Cover
    type:  url
